FROM node:22-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package*.json ./

RUN pnpm install

RUN apk add --no-cache postgresql-client bash

COPY . .

EXPOSE 3000 5432 5555

CMD sh -c "pnpm prisma generate && pnpm prisma migrate dev --name init && pnpm prisma db seed && pnpm run start:dev"